name: Node CI

on:
  push:
    branches: [ istiaque_ci ]
  pull_request:
    branches: [ istiaque_ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run build
      run: npm run build
    - name: Run tests
      run: npm run test
